version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build: ./app
    image: qdt/app
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - api

  api:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build: ./api
    image: qdt/api
    volumes:
      - .:/api
      - /api/node_modules
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  
  redis:
    image: redis
    depends_on:
      - db
      
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgre-db:/data/db



volumes:
  postgre-db: